### PR TITLE
babel 6 changes export default

### LINKED ISSUE #40: babel 6 changes export default
I'm getting the following error:

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `exports`.

In your transpiled code there is the expression "exports.default = DrawerLayout". Therefore, I'd have to require it like that: `require('react-native-drawer-layout').default`. I guess that others might be surprised, too, so I'd suggest we make it work like before.

```
const React = require('react-native');
const { Platform } = React;

if (Platform.OS === 'android') {
  module.exports = require('./DrawerLayout.android');
} else if (Platform.OS === 'ios') {
  module.exports = require('./DrawerLayout.ios').default;
}
```

### PR DESCRIPTION
**Pull request by webwelten**
Fixes #40

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Hi there, 

First of all thanks for the feedback, I wasn't aware of that change. 

@brentvatne @mfmendiola What do you guys think about this solution, compared to e.g. using the [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) module? (it would do the same, but we wouldn't need to modify our source code in order to fit the compiler). I mean on the long run, after I tested this PR I will merge it and deploy a version with this bugfix included.

**Comment by DanielMSchmidt** [comment]
@webwelten Thanks for the PR, I will include it in the 0.3.4 release.

**Comment by brentvatne** [comment]
:rocket:

@DanielMSchmidt - seems safer to depend on this than a babel plugin :)

**Comment by DanielMSchmidt** [comment]
@brentvatne Okay, let's keep it that way ;)

**Pull request merged**
