### PR TITLE
translate to es6 & add positions constants

### PR DESCRIPTION
**Pull request by rosko**
#14

### CODE REVIEW

**Comment by rosko** [comment]
also fix for #11

**Comment by mfmendiola** [comment]
@rosko Thanks! Lgtm!  Would you mind rebasing and squashing?

@DanielMSchmidt I know you had some thoughts on this issue.  Are you okay with this solution?

**Comment by mfmendiola** [comment]
@rosko If this lands, would you also mind updating the documentation?

**Comment by DanielMSchmidt** [comment]
@mfmendiola To my mind this would not be an ideal solution, because this library was written with the new ES6 and ES7 features and just rewriting it to only use ES5 is not much of an elegant solution to me. At the dotJS there was a talk about authoring and publishing ES6 modules, the solution shown there would be a nicer one to my mind. [Link to the slides](http://slides.com/vvo/authoring-and-publishing-es6-modules-today-dotjs-2015) 

To my mind this would be little overhead and the code may be in the nicer ES6 syntax. But in the end it doesn't really matter which approach we use, at long as it fixes the bug ;)

EDIT: especially pages 13 to 16 are relevant :)

**Comment by mfmendiola** [comment]
@DanielMSchmidt Thanks for the tip! I'll have a look at the slides sometime in the next few days.

**Comment by mfmendiola** [comment]
@DanielMSchmidt added pre-publishing transpilation to es5 here: https://github.com/iodine/react-native-drawer-layout/pull/21.  However, we should still keep the change to fix #11 here.  @rosko Would you mind reverting the `autobind-decorator` changes, squashing, and rebasing?  Thanks!

**Comment by mfmendiola** [comment]
fixed here: https://github.com/iodine/react-native-drawer-layout/pull/23

**Pull request closed without merging**
