### PR TITLE
Moved from babel5 to babel6

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
I did this in preparation for the tests and also moved the source into a `src` folder, as it is easier to specify the test target and it is clearer that these files are not the ones beeing delivered.
Babel6 seems to have other default preferences, should I try to get the dist code generated in a not minified way?

Have a nice day!

### CODE REVIEW

**Comment by mfmendiola** [comment]
lgtm!  Yes, I think a non-minified version will make debugging a bit easier for the end user :smile:

**Comment by DanielMSchmidt** [comment]
Roger that, I'll be searching for a flag and merge the pr

**Comment by DanielMSchmidt** [comment]
@mfmendiola lgty?

**Comment by mfmendiola** [comment]
lgtm

**Pull request merged**
