### PR TITLE
Added linting and fixed linting errors

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Also added a small section for contributors in the readme. 
I chose xo as a linter as it is based on eslint but needs less configuration and seems pretty nice.
I hope you like the linting settings, if not please let me know, I will happily alter them to fit our needs.

P.S.: [Here are images of how the CI may look like](http://imgur.com/a/0NTB5), as mentioned in #24

### CODE REVIEW

**Comment by brentvatne** [comment]
Hey @DanielMSchmidt - I've added you as a collaborator on this repo, which means you can merge your own pull requests now :) cc @mfmendiola 

These changes look great to me.

Let me know your npm username and I'll add you as an owner on there so you can push new versions. Thanks for the help!

**Comment by mfmendiola** [comment]
sounds great! thanks @brentvatne

**Comment by DanielMSchmidt** [comment]
@brentvatne Thanks a lot, I am glad you chose me to be in the team ;) I will try to resolve the merge conflicts later today. My npm username is dschmidt

**Comment by DanielMSchmidt** [comment]
@mfmendiola @brentvatne Who should be contacted for a Circle CI account? They say the repo admin, who is this in our case? Would be so cool to have a build flag in the readme ;)

**Comment by mfmendiola** [comment]
Thanks @DanielMSchmidt.  I can go ahead and set one up tonight.

**Comment by DanielMSchmidt** [comment]
@mfmendiola Awesome!

**Comment by brentvatne** [comment]
Did you guys get circle set up? @mfmendiola @DanielMSchmidt

**Comment by mfmendiola** [comment]
Set up here: https://github.com/iodine/react-native-drawer-layout/pull/36

**Pull request merged**
