### PR TITLE
Update to add openDrawer and closeDrawer Methods

### PR DESCRIPTION
**Pull request by stephenkeep**
Simple update to add openDrawer and closeDrawer Methods so that iOS matches the Android implementation.

### CODE REVIEW

**Comment by brentvatne** [comment]
Hi @stephenkeep! Thanks for the PR -- I think what we should do instead of creating separate methods for these is rename the `open` and `close` methods to `openDrawer` and `closeDrawer` :)

**Comment by stephenkeep** [comment]
I thought that too but kept it there for backwards compatibility. I did not want to break any apps that are currently using open and close.

Im happy either way :)

**Comment by brentvatne** [comment]
Probably not worth maintaining backwards compatibility on this small thing but I can definitely appreciate your consideration :) We can just bump version to indicate breaking API change

**Comment by stephenkeep** [comment]
Sounds good, I have updated the major release version and renamed the open and close methods.

**Comment by skv-headless** [comment]
Hi @stephenkeep I think we also need to change `this.close` to `this.closeDrawer` inside component. If you don't have time I can do it.

**Comment by brentvatne** [comment]
Thanks @stephenkeep and @skv-headless! This is merged now in #10

**Pull request closed without merging**
